services:
  db_test:
    image: postgres:17
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - '${POSTGRES_PORT_TEST}:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
